version: "1.0"

services:
    payment-database:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: rootUser
          MONGO_INITDB_ROOT_PASSWORD: rootPassword
        ports:
            - "27019:27017"
        container_name: payment-database
        networks:
            - foodtotem-network
    payment-api:
        build:
          context: ../../src
          dockerfile: Dockerfile
        environment:
          PaymentDatabaseSettings__ConnectionString: mongodb://rootUser:rootPassword@payment-database:27017
          AccessToken: "<AccessToken>"
          ExternalPosId: "<ExternalPosId>"
          UserId: "<UserId>"
          BaseUrl: "<BaseUrl>"
        ports:
            - "3002:80"
        depends_on:
            - payment-database
        networks:
            - foodtotem-network
        restart: always
networks:
    foodtotem-network:
        driver: bridge

    
    