name: build

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update AppSettings
        uses: microsoft/variable-substitution@v1
        with:
          files: src/Adapters/Driver/FoodTotem.Payment.API/appsettings.json
        env:
          AccessToken: ${{ secrets.MERCADO_PAGO_ACCESS_TOKEN }}
          ExternalPosId: ${{ secrets.MERCADO_PAGO_EXTERNAL_POS_ID }}
          UserId: ${{ secrets.MERCADO_PAGO_USER_ID }}
          BaseUrl: ${{ secrets.MERCADO_PAGO_API_URL }}
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra/terraform
  
      - name: Terraform Plan
        if: github.ref == 'refs/heads/main'
        run: terraform plan
        working-directory: ./infra/terraform
        env:
          TF_VAR_lab_account_id: ${{ secrets.LAB_ACCOUNT_ID }}
          TF_VAR_lab_account_region: ${{ secrets.LAB_ACCOUNT_REGION }}
          TF_VAR_food_totem_payment_image: ${{ secrets.PAYMENT_IMAGE }}
          TF_VAR_mongo_image: ${{ secrets.MONGO_IMAGE }}
          TF_VAR_mongo_root_password: ${{ secrets.MONGO_ROOT_PASSWORD }}
          TF_VAR_mongo_user: ${{ secrets.MONGO_USER }}