name: deploy

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update AppSettings
      uses: microsoft/variable-substitution@v1
      with:
        files: src/Adapters/Driver/FoodTotem.Payment.API/appsettings.json
      env:
        ConnectionStrings.DefaultConnection: ${{ secrets.DOCUMENT_DB_CONNECTION_STRING }}
 
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Docker Setup QEMU
      if: github.ref == 'refs/heads/main'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: amd64,arm64
    - name: Set-up Docker Buildx
      if: github.ref == 'refs/heads/main'
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        context: src
        file: src/Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/food-totem-payment-api:latest